version: 2

models:
  - name: int__subscription_monthly_snapshots
    description: "Monthly snapshots of active subscriptions for ARR metrics."
    columns:
      - name: subscription_id
        tests: [not_null]
      - name: month_start
        tests: [not_null]
